[routers]
router1 ansible_host=localhost ansible_port=2221
router2 ansible_host=localhost ansible_port=2222
router3 ansible_host=localhost ansible_port=2223

[routers:vars]
ansible_user=admin
ansible_password=MotDePasseTemporaire
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
