- name: Configure FRRouting
  hosts: routers
  become: true

  tasks:

    - name: Generate FRR configuration from template
      template:
        src: "../templates/frr.conf.j2"
        dest: "/etc/frr/frr.conf"
        owner: frr
        group: frr
        mode: "0640"

    - name: Enable ospfd
      replace:
        path: /etc/frr/daemons
        regexp: '^ospfd=no'
        replace: 'ospfd=yes'

    - name: Restart FRR
      command: /usr/lib/frr/frrinit.sh restart
